- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/host
  value: ((terraform_outputs.staging_credhub_rds_host))

- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/port
  value: ((terraform_outputs.staging_credhub_rds_port))

- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/username
  value: ((terraform_outputs.staging_credhub_rds_username))

- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/password
  value: ((terraform_outputs.staging_credhub_rds_password))

- type: replace
  path: /vm_extensions/name=credhub-lb/cloud_properties/lb_target_groups
  value: [((terraform_outputs.staging_credhub_lb_target_group))]  
    