deployment_name: credhub-production
common_name: credhub.fr.cloud.gov
instances: 2
azs: [z1,z2]
network_name: production-credhub
credhub_vm_type: t3.medium
credhub_lb_vm_extension: production-credhub-lb
pipeline-tasks-git-url: https://github.com/18F/cg-pipeline-tasks
pipeline-tasks-git-branch: master